- name: "Set photoprism server facts"
  set_fact:
    photoprism_server_url: "{{ photoprism.server.name }}.{{ common.namespace }}.svc.cluster.local"

- name: "Run deployment"
  include_tasks: "roles/common/tasks/apply.yml"
  vars:
    resources: "{{ role_path }}/templates/server/"
    name: "{{ photoprism.server.name }}"
    deployment_timeout: 12
    storages:
      - dir: "{{ photoprism.server.storageData.dir }}"
        setup: "{{ photoprism.server.storageData.setup | default(omit) }}"
        host: "{{ photoprism.server.storageData.host | default(omit) }}"
        nfs: "{{ photoprism.server.storageData.nfs | default(omit) }}"
        mode: "0775"
        uid: "{{ photoprism.server.uid }}"
        gid: "{{ photoprism.server.gid }}"
      - dir: "{{ photoprism.server.storageOriginals.dir }}"
        setup: "{{ photoprism.server.storageOriginals.setup | default(omit) }}"
        host: "{{ photoprism.server.storageOriginals.host | default(omit) }}"
        nfs: "{{ photoprism.server.storageOriginals.nfs | default(omit) }}"
        mode: "0775"
        uid: "{{ photoprism.server.uid }}"
        gid: "{{ photoprism.server.gid }}"
      - dir: "{{ photoprism.server.storageImport.dir }}"
        setup: "{{ photoprism.server.storageImport.setup | default(omit) }}"
        host: "{{ photoprism.server.storageImport.host | default(omit) }}"
        nfs: "{{ photoprism.server.storageImport.nfs | default(omit) }}"
        mode: "0775"
        uid: "{{ photoprism.server.uid }}"
        gid: "{{ photoprism.server.gid }}"
      - dir: "{{ photoprism.server.storageExport.dir }}"
        setup: "{{ photoprism.server.storageExport.setup | default(omit) }}"
        host: "{{ photoprism.server.storageExport.host | default(omit) }}"
        nfs: "{{ photoprism.server.storageExport.nfs | default(omit) }}"
        mode: "0775"
        uid: "{{ photoprism.server.uid }}"
        gid: "{{ photoprism.server.gid }}"
