- name: "Set photoprism server facts"
  set_fact:
    photoprism_server_url: "{{ photoprism.server.name }}.{{ common.namespace }}.svc.cluster.local"

- name: "Run deployment"
  include_tasks: "roles/common/tasks/apply.yml"
  vars:
    resources: "{{ role_path }}/templates/server/"
    name: "{{ photoprism.server.name }}"
    deployment_timeout: 12
    storages:
      - dir: "{{ photoprism.server.storage.dir }}"
        setup: "{{ photoprism.server.storage.setup | default(omit) }}"
        host: "{{ photoprism.server.storage.host | default(omit) }}"
        nfs: "{{ photoprism.server.storage.nfs | default(omit) }}"
        mode: "0775"
        uid: 1000
        gid: 1000
