- name: "Set gitlab cache facts"
  set_fact:
    gitlab_cache_url: "{{ gitlab.cache.name }}.{{ common.namespace }}.svc.cluster.local"

- name: "Run deployment"
  include_tasks: "roles/common/tasks/apply.yml"
  vars:
    resources: "{{ role_path }}/templates/cache/"
    name: "{{ gitlab.cache.name }}"
    deployment_timeout: 12
    storages:
      - dir: "{{ gitlab.cache.storage.dir }}"
        setup: "{{ gitlab.cache.storage.setup | default(omit) }}"
        host: "{{ gitlab.cache.storage.host | default(omit) }}"
        nfs: "{{ gitlab.cache.storage.nfs | default(omit) }}"
        mode: "0775"
        uid: "{{ gitlab.cache.uid }}"
        gid: "{{ gitlab.cache.gid }}"
