- name: "Set gitlab kroki facts"
  set_fact:
    gitlab_kroki_url: "{{ gitlab.kroki.name }}.{{ common.namespace }}.svc.cluster.local"

- name: "Run deployment"
  include_tasks: "roles/common/tasks/apply.yml"
  vars:
    resources: "{{ role_path }}/templates/kroki/"
    name: "{{ gitlab.kroki.name }}"
    deployment_timeout: 6
    storages: []
