- name: "Set gitlab kroki-bpmn facts"
  set_fact:
    gitlab_kroki_bpmn_url: "{{ gitlab.krokiBpmn.name }}.{{ common.namespace }}.svc.cluster.local"

- name: "Run deployment"
  include_tasks: "roles/common/tasks/apply.yml"
  vars:
    resources: "{{ role_path }}/templates/kroki-bpmn/"
    name: "{{ gitlab.krokiBpmn.name }}"
    deployment_timeout: 6
    storages: []
