- name: "Set gitlab kroki-excalidraw facts"
  set_fact:
    gitlab_kroki_excalidraw_url: "{{ gitlab.krokiExcalidraw.name }}.{{ common.namespace }}.svc.cluster.local"

- name: "Run deployment"
  include_tasks: "roles/common/tasks/apply.yml"
  vars:
    resources: "{{ role_path }}/templates/kroki-excalidraw/"
    name: "{{ gitlab.krokiExcalidraw.name }}"
    deployment_timeout: 6
    storages: []
