- name: "Deploy redis"
  include_tasks: "redis.yml"
  when: gitlab.enabled

- name: "Deploy cache"
  include_tasks: "cache.yml"
  when: gitlab.enabled

- name: "Deploy storage"
  include_tasks: "storage.yml"
  when: gitlab.enabled

- name: "Deploy kroki-blockdiag"
  include_tasks: "kroki-blockdiag.yml"
  when: gitlab.enabled

- name: "Deploy kroki-bpmn"
  include_tasks: "kroki-bpmn.yml"
  when: gitlab.enabled

- name: "Deploy kroki-excalidraw"
  include_tasks: "kroki-excalidraw.yml"
  when: gitlab.enabled

- name: "Deploy kroki-mermaid"
  include_tasks: "kroki-mermaid.yml"
  when: gitlab.enabled

- name: "Deploy kroki"
  include_tasks: "kroki.yml"
  when: gitlab.enabled

- name: "Deploy server"
  include_tasks: "server.yml"
  when: gitlab.enabled
