- name: "Set gitlab redis facts"
  set_fact:
    gitlab_redis_url: "{{ gitlab.redis.name }}.{{ common.namespace }}.svc.cluster.local"

- name: "Run deployment"
  include_tasks: "roles/common/tasks/apply.yml"
  vars:
    resources: "{{ role_path }}/templates/redis/"
    name: "{{ gitlab.redis.name }}"
    deployment_timeout: 12
    storages: []
