- name: "Set gitlab runner facts"
  set_fact:
    gitlab_runner_url: "{{ gitlab.runner.name }}.{{ common.namespace }}.svc.cluster.local"
    runner_entrypoint_sh: "{{ lookup('template', role_path + '/templates/runner-entrypoint.sh.j2') }}"
    runner_config_toml: "{{ lookup('template', role_path + '/templates/runner-config.toml.j2') }}"

- name: "Run deployment"
  include_tasks: "roles/common/tasks/apply.yml"
  vars:
    resources: "{{ role_path }}/templates/runner/"
    name: "{{ gitlab.runner.name }}"
    deployment_timeout: 12
    storages: []
