- name: "Set gitlab server facts"
  set_fact:
    gitlab_server_url: "{{ gitlab.server.name }}.{{ common.namespace }}.svc.cluster.local"
    omnibus_conf: "{{ lookup('template', role_path + '/templates/omnibus.conf.j2') }}"

- name: "Run deployment"
  include_tasks: "roles/common/tasks/apply.yml"
  vars:
    resources: "{{ role_path }}/templates/server/"
    name: "{{ gitlab.server.name }}"
    deployment_timeout: 90
    storages:
      - dir: "{{ gitlab.server.storageGit.dir }}"
        setup: "{{ gitlab.server.storageGit.setup | default(omit) }}"
        host: "{{ gitlab.server.storageGit.host | default(omit) }}"
        nfs: "{{ gitlab.server.storageGit.nfs | default(omit) }}"
        mode: "0755"
        uid: 0
        gid: 0
      - dir: "{{ gitlab.server.storageLogs.dir }}"
        setup: "{{ gitlab.server.storageLogs.setup | default(omit) }}"
        host: "{{ gitlab.server.storageLogs.host | default(omit) }}"
        nfs: "{{ gitlab.server.storageLogs.nfs | default(omit) }}"
        mode: "0755"
        uid: 0
        gid: 0
      - dir: "{{ gitlab.server.storageConfig.dir }}"
        setup: "{{ gitlab.server.storageConfig.setup | default(omit) }}"
        host: "{{ gitlab.server.storageConfig.host | default(omit) }}"
        nfs: "{{ gitlab.server.storageConfig.nfs | default(omit) }}"
        mode: "0755"
        uid: 0
        gid: 0
      - dir: "{{ gitlab.server.storageBuilds.dir }}"
        setup: "{{ gitlab.server.storageBuilds.setup | default(omit) }}"
        host: "{{ gitlab.server.storageBuilds.host | default(omit) }}"
        nfs: "{{ gitlab.server.storageBuilds.nfs | default(omit) }}"
        mode: "0755"
        uid: 0
        gid: 0
      - dir: "{{ gitlab.server.storageSsh.dir }}"
        setup: "{{ gitlab.server.storageSsh.setup | default(omit) }}"
        host: "{{ gitlab.server.storageSsh.host | default(omit) }}"
        nfs: "{{ gitlab.server.storageSsh.nfs | default(omit) }}"
        mode: "0755"
        uid: 0
        gid: 0
      - dir: "{{ gitlab.server.storageShared.dir }}"
        setup: "{{ gitlab.server.storageShared.setup | default(omit) }}"
        host: "{{ gitlab.server.storageShared.host | default(omit) }}"
        nfs: "{{ gitlab.server.storageShared.nfs | default(omit) }}"
        mode: "0755"
        uid: 0
        gid: 0
