- name: "Set gitlab storage facts"
  set_fact:
    gitlab_storage_url: "{{ gitlab.storage.name }}.{{ common.namespace }}.svc.cluster.local"

- name: "Run deployment"
  include_tasks: "roles/common/tasks/apply.yml"
  vars:
    resources: "{{ role_path }}/templates/storage/"
    name: "{{ gitlab.storage.name }}"
    deployment_timeout: 12
    storages:
      - dir: "{{ gitlab.storage.storage.dir }}"
        setup: "{{ gitlab.storage.storage.setup | default(omit) }}"
        host: "{{ gitlab.storage.storage.host | default(omit) }}"
        nfs: "{{ gitlab.storage.storage.nfs | default(omit) }}"
        mode: "0775"
        uid: "{{ gitlab.storage.uid }}"
        gid: "{{ gitlab.storage.gid }}"
