{{ include "service-spec" (dict 
  "Values" .Values
  "Release" .Release
  "Chart" .Chart
  "component" "server"
  "service" .Values.postgres.server.service
  "ports" .Values.postgres.server.ports) }}
