{{ include "deployment-spec" (dict 
  "Values" .Values
  "Release" .Release
  "Chart" .Chart
  "component" "backup") }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  revisionHistoryLimit: 0
  {{- include "selector-spec" (dict "Chart" .Chart "component" "backup") | nindent 2 }}
  template:
    {{- include "metadata-spec" (dict 
      "Values" .Values
      "Release" .Release
      "Chart" .Chart
      "component" "backup"
      "annotations" .Values.backup.pod.annotations) | nindent 4}}
    spec:
      serviceAccountName: "{{ .Chart.Name }}-backup"
      securityContext:
        runAsUser: {{ .Values.backup.uid }}
        runAsGroup: {{ .Values.backup.gid }}
        fsGroup: {{ .Values.backup.gid }}
      {{- with .Values.backup.pullSecret }}
      imagePullSecrets:
        - name: "{{ . }}"
      {{- end }}
      initContainers:
        {{- include "init-postgres-wait" (dict "Values" .Values "Release" .Release "Chart" .Chart) | nindent 8 }}
      containers:
        - name: "{{ .Chart.Name }}-backup"
          image: "{{ .Values.backup.image.name }}:{{ .Values.backup.image.tag }}"
          imagePullPolicy: "{{ .Values.backup.image.pullPolicy }}"
          env:
            - name: POSTGRES_HOST
              value: "{{ .Chart.Name }}-server.{{ .Release.Namespace }}.svc.cluster.local"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Chart.Name }}-server"
                  key: password
                  optional: false
            - name: POSTGRES_USER
              value: "{{ .Values.server.user }}"
            - name: POSTGRES_CLUSTER
              value: "TRUE"
            - name: POSTGRES_DB
              value: "{{ .Values.server.database }}"
            - name: POSTGRES_EXTRA_OPTS
              value: "{{ .Values.backup.extra }}"
            - name: SCHEDULE
              value: "{{ .Values.backup.schedule }}"
            - name: BACKUP_KEEP_DAYS
              value: "{{ .Values.backup.keepDays }}"
            - name: BACKUP_KEEP_WEEKS
              value: "{{ .Values.backup.keepWeeks }}"
            - name: BACKUP_KEEP_MONTHS
              value: "{{ .Values.backup.keepMonths }}"
            - name: HEALTHCHECK_PORT
              value: "8080"
          {{- with .Values.backup.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: healthcheck
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: healthcheck
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /
              port: healthcheck
            failureThreshold: 1
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          resources:
            {{- toYaml .Values.backup.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: "data-volume"
              mountPath: "/backups"
      nodeSelector:
        {{- toYaml .Values.backup.nodeSelector | nindent 8 }}
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: "{{ .Chart.Name }}-backup-data"
