{{ include "service-spec" (dict 
  "Values" .Values
  "Release" .Release
  "Chart" .Chart
  "component" "backup"
  "service" .Values.postgres.backup.service
  "ports" .Values.postgres.backup.ports) }}
