apiVersion: apps/v1
kind: Deployment
{{ include "metadata-spec" (dict 
  "Values" .Values
  "Release" .Release
  "Chart" .Chart
  "component" "server") }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  revisionHistoryLimit: 0
  {{- include "selector-spec" (dict "Chart" .Chart "component" "server") | nindent 2 }}
  template:
    {{- include "metadata-spec" (dict 
      "Values" .Values
      "Release" .Release
      "Chart" .Chart
      "component" "server"
      "annotations" .Values.keel.server.pod.annotations) | nindent 4}}
    spec:
      serviceAccountName: "{{ .Chart.Name }}-server"
      securityContext:
        runAsUser: {{ .Values.keel.server.uid }}
        runAsGroup: {{ .Values.keel.server.gid }}
        fsGroup: {{ .Values.keel.server.gid }}
      {{- with .Values.keel.server.pullSecret }}
      imagePullSecrets:
        - name: "{{ . }}"
      {{- end }}
      containers:
        - name: "{{ .Chart.Name }}-server"
          image: "{{ .Values.keel.server.image.name }}:{{ .Values.keel.server.image.tag }}"
          imagePullPolicy: "{{ .Values.keel.server.image.pullPolicy }}"
          command:
            - '/bin/keel'
          env:
            - name: "NAMESPACE"
              value: "{{ .Release.Namespace }}"
            - name: "XDG_DATA_HOME"
              value: "/data"
            - name: "POLL"
              value: "true"
            - name: "DEBUG"
              value: "true"
            - name: "INSECURE_REGISTRY"
              value: "true"
            - name: "BASIC_AUTH_USER"
              valueFrom:
                secretKeyRef:
                  name: "{{ .Chart.Name }}-server"
                  key: "username"
                  optional: false
            - name: "BASIC_AUTH_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: "{{ .Chart.Name }}-server"
                  key: "password"
                  optional: false
          {{- with .Values.keel.server.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: web
              containerPort: 9300
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: web
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /healthz
              port: web
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          resources:
            {{- toYaml .Values.keel.server.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: "data-volume"
              mountPath: /data
      nodeSelector:
        {{- toYaml .Values.keel.server.nodeSelector | nindent 8 }}
      volumes:
        - name: "data-volume"
          persistentVolumeClaim:
            claimName: "{{ .Chart.Name }}-server-data"
