apiVersion: v1
kind: Secret
{{ include "metadata-spec" (dict 
  "Values" .Values
  "Release" .Release
  "Chart" .Chart
  "component" "server") }}
type: "Opaque"
data:
  username: "{{ .Values.keel.server.auth.username | b64enc }}"
  password: "{{ .Values.keel.server.auth.password | b64enc }}"
