- name: "Set phpldapadmin server facts"
  set_fact:
    phpldapadmin_server_url: "{{ phpldapadmin.server.name }}.{{ common.namespace }}.svc.cluster.local"

- name: "Run deployment"
  include_tasks: "roles/common/tasks/apply.yml"
  vars:
    resources: "{{ role_path }}/templates/server/"
    name: "{{ phpldapadmin.server.name }}"
    deployment_timeout: 12
