- name: "Check if config file {{ include_vars_path }} exists"
  stat:
    path: include_vars_path
  register: config_stat_result

- name: "Load config file "
  ansible.builtin.include_vars:
    file: "{{ include_vars_path }}"
    hash_behaviour: merge
  when: config_stat_result.stat.exists

- name: "Set common facts"
  set_fact:
    storage_options_template: "{{ playbook_dir }}/roles/k8s/templates/storage_spec.yml.j2"

- name: "Create namespace - {{ common.namespace }}"
  kubernetes.core.k8s:
    name: "{{ common.namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: "Prepare root storage"
  file:
    path: "{{ common.storage.path }}"
    state: directory
    mode: "0755"
  become: yes
  when: common.storage.type == 'host'
