apiVersion: v1
kind: Secret
{{ include "metadata-spec" (dict 
  "Values" .Values
  "Release" .Release
  "Chart" .Chart
  "component" "redis") }}
type: "Opaque"
data:
  password: "{{ .Values.authelia.redis.password | b64enc }}"
