- hosts: hosts
  roles:
    - role: common
      tags: homelab

    - role: postgres
      tags: homelab

    - role: mariadb
      tags: homelab

    - role: openldap
      tags: homelab

    - role: traefik
      tags: homelab

    - role: homer
      tags: homelab

    - role: errorpage
      tags: homelab

    - role: vigil
      tags: homelab

    - role: phpldapadmin
      tags: homelab

    - role: authelia
      tags: homelab

    - role: filebrowser
      tags: homelab

    - role: adminer
      tags: homelab

    - role: photoprism
      tags: homelab

    - role: send
      tags: homelab

    - role: matrix
      tags: homelab

    - role: gitlab
      tags: homelab

    - role: registry
      tags: experimental_registry
