---
nextcloud:
  server:
    # Name of the component.
    # type: string
    name: "nextcloud-server"

    # Docker image for the Authelia server.
    image:
      # Image name without the tag.
      # type: string
      name: "docker.io/library/nextcloud"

      # Image tag.
      # type: string
      tag: "22"

      # Image pull policy.
      # type: string
      pullPolicy: "IfNotPresent"

    # Subdomain at which to host the web GUI.
    # type: string
    subdomain: "nextcloud"

    # Admin (root) user options.
    admin:
      # Name for the admin user.
      # type: string
      user: "admin"

      # Password for the admin user.
      # type: string
      password: "Password1!"

    # Database options.
    database:
      # Name of the database. The database will be created if it does not exist.
      # type: string
      name: "nextcloud"

      # Role for the database. The role will be created if it does not exist.
      # type: string
      role: "nextcloud"

      # Role password for the database.
      # type: string
      password: "Password1!"

    # Storage options for the nextcloud data.
    # This will be used for nextcloud config and app data only.
    # The user files are stored in minio (S3).
    storage:
      # Capacity to request.
      # type: string
      capacity: "1Gi"

      # Storage subdirectory
      # type: string
      dir: "nextcloud/server"

    # S3 user files
    s3:
      # Name of the bucket to use for user files.
      # type: string
      bucket: "nextcloud"

      # S3 region.
      # type: string
      region: "us-east-1"

    # Additional environment variables for the pod.
    # type: map
    # example: { "MY_ENV_KEY": "some_value" }
    env: {}

    # The kubernetes service type.
    # type: string
    serviceType: "ClusterIP"

    # Additional annotations to add to the service.
    # type: map
    # example: { "example.com/hello": "world" }
    serviceAnnotations: {}

    # Additional labels to add to the service.
    # type: map
    # example: { "example.com/hello": "world" }
    serviceLabels: {}
    
    # Additional annotations to add to the pod.
    # type: map
    # example: { "example.com/hello": "world" }
    podAnnotations: {}

    # Additional labels to add to the pod.
    # type: map
    # example: { "example.com/hello": "world" }
    podLabels: {}

    # Specify which node or nodes can be used to host this pod.
    # Leave as an empty map to allow the pod to be spawned anywhere.
    # type: map
    # example: { "kubernetes.io/arch": "amd64" }
    nodeSelector: {}

    # Optionally specify how much of each resource the pod will need.
    resources:
      # Maximum limits that the pod can not exceed.
      # Set to ~ or null to disable the resource limits.
      limits:
        # Maximum CPU that the pod can not exceed.
        # type: string
        # example: "1000m"
        cpu: ~
        # Maximum RAM that the pod can not exceed.
        # type: string
        # example: "1024Mi"
        memory: ~
      # Requested limits for scheduling the pod on nodes.
      # Set to ~ or null to disable the resource requests.
      requests:
        # The requested amount of CPU
        # type: string
        # example: "500m"
        cpu: ~
        # The requested amount of CPU
        # type: string
        # example: "512Mi"
        memory: ~
  redis:
    # Name of the component.
    # type: string
    name: "nextcloud-redis"

    # Docker image for the redis cache.
    image:
      # Image name without the tag.
      # type: string
      name: "docker.io/library/redis"

      # Image tag.
      # type: string
      tag: "latest"

      # Image pull policy.
      # type: string
      pullPolicy: "IfNotPresent"

    # Password for connecting to the redis.
    # type: string
    password: "Password1!"

    # Additional environment variables for the pod.
    # type: map
    # example: { "MY_ENV_KEY": "some_value" }
    env: {}

    # The kubernetes service type.
    # type: string
    serviceType: "ClusterIP"

    # Additional annotations to add to the service.
    # type: map
    # example: { "example.com/hello": "world" }
    serviceAnnotations: {}

    # Additional labels to add to the service.
    # type: map
    # example: { "example.com/hello": "world" }
    serviceLabels: {}

    # Additional annotations to add to the pod.
    # type: map
    # example: { "example.com/hello": "world" }
    podAnnotations: {}

    # Additional labels to add to the pod.
    # type: map
    # example: { "example.com/hello": "world" }
    podLabels: {}

    # Specify which node or nodes can be used to host this pod.
    # Leave as an empty map to allow the pod to be spawned anywhere.
    # type: map
    # example: { "kubernetes.io/arch": "amd64" }
    nodeSelector: {}

    # Optionally specify how much of each resource the pod will need.
    resources:
      # Maximum limits that the pod can not exceed.
      # Set to ~ or null to disable the resource limits.
      limits:
        # Maximum CPU that the pod can not exceed.
        # type: string
        # example: "1000m"
        cpu: ~
        # Maximum RAM that the pod can not exceed.
        # type: string
        # example: "1024Mi"
        memory: ~
      # Requested limits for scheduling the pod on nodes.
      # Set to ~ or null to disable the resource requests.
      requests:
        # The requested amount of CPU
        # type: string
        # example: "500m"
        cpu: ~
        # The requested amount of CPU
        # type: string
        # example: "512Mi"
        memory: ~

  minio:
    # Name of the component.
    # type: string
    name: "nextcloud-minio"

    # Docker image for the minio storage.
    image:
      # Image name without the tag.
      # type: string
      name: "docker.io/minio/minio"

      # Image tag.
      # type: string
      tag: "latest"

      # Image pull policy.
      # type: string
      pullPolicy: "IfNotPresent"

    # Value for the access key name.
    # type: string
    accessKey: "minio"

    # Value for the access key secret.
    # type: string
    secretKey: "Password1!"

    # Storage for user files.
    storage:
      # Capacity to request.
      # type: string
      capacity: "20Gi"

      # Storage subdirectory
      # type: string
      dir: "nextcloud/minio"

    # Additional environment variables for the pod.
    # type: map
    # example: { "MY_ENV_KEY": "some_value" }
    env: {}

    # The kubernetes service type.
    # type: string
    serviceType: "ClusterIP"

    # Additional annotations to add to the service.
    # type: map
    # example: { "example.com/hello": "world" }
    serviceAnnotations: {}

    # Additional labels to add to the service.
    # type: map
    # example: { "example.com/hello": "world" }
    serviceLabels: {}

    # Additional annotations to add to the pod.
    # type: map
    # example: { "example.com/hello": "world" }
    podAnnotations: {}

    # Additional labels to add to the pod.
    # type: map
    # example: { "example.com/hello": "world" }
    podLabels: {}

    # Specify which node or nodes can be used to host this pod.
    # Leave as an empty map to allow the pod to be spawned anywhere.
    # type: map
    # example: { "kubernetes.io/arch": "amd64" }
    nodeSelector: {}

    # Optionally specify how much of each resource the pod will need.
    resources:
      # Maximum limits that the pod can not exceed.
      # Set to ~ or null to disable the resource limits.
      limits:
        # Maximum CPU that the pod can not exceed.
        # type: string
        # example: "1000m"
        cpu: ~
        # Maximum RAM that the pod can not exceed.
        # type: string
        # example: "1024Mi"
        memory: ~
      # Requested limits for scheduling the pod on nodes.
      # Set to ~ or null to disable the resource requests.
      requests:
        # The requested amount of CPU
        # type: string
        # example: "500m"
        cpu: ~
        # The requested amount of CPU
        # type: string
        # example: "512Mi"
        memory: ~
