{{- include "configmap-spec" (dict 
  "Values" .Values
  "Release" .Release
  "Chart" .Chart
  "component" "server") }}
data:
  "config.yml": |
    title: "{{ .Values.global.domain }}"
    subtitle: "Dashboard"
    icon: "fas fa-server"

    header: true
    footer: false

    columns: "3"
    connectivityCheck: false

    defaults:
      layout: list
      colorTheme: auto

    theme: {{ .Values.server.theme }}

    services:
      - name: "Applications"
        icon: "fas fa-code-branch"
        items:
          {{- if .Values.global.deploy.drawio }}
          - name: "Draw.io"
            icon: "fas fa-pen-nib"
            subtitle: "Diagramming/whiteboarding visualization application"
            tag: "draw"
            url: "https://{{ .Values.global.drawio.server.subdomain }}.{{ .Values.global.domain }}/"
          {{- end }}
          {{- if .Values.global.deploy.haste }}
          - name: "Hastebin"
            icon: "fas fa-file-pen"
            subtitle: "Haste is an open-source pastebin software"
            tag: "text"
            url: "https://{{ .Values.global.haste.server.subdomain }}.{{ .Values.global.domain }}/"
          {{- end }}
          {{- if .Values.global.deploy.gitlab }}
          - name: "GitLab"
            icon: "fa-brands fa-gitlab"
            subtitle: "Code repository and collaborative software"
            tag: "git"
            url: "https://{{ .Values.global.gitlab.server.subdomain }}.{{ .Values.global.domain }}/"
          {{- end }}
          {{- if .Values.global.deploy.gitlab }}
          - name: "Matrix"
            icon: "fas fa-comment"
            subtitle: "An open standard real-time communication"
            tag: "chat"
            url: "https://{{ .Values.global.matrix.element.subdomain }}.{{ .Values.global.domain }}/"
          {{- end }}
          {{- if .Values.global.deploy.joplin }}
          - name: "Joplin Server"
            icon: "fa-solid fa-book"
            subtitle: "Sync server for Joplin a note taking application"
            tag: "notes"
            url: "https://{{ .Values.global.joplin.server.subdomain }}.{{ .Values.global.domain }}/"
          {{- end }}
          {{- if .Values.global.deploy.hedgedoc }}
          - name: "HedgeDoc"
            icon: "fa-brands fa-markdown"
            subtitle: "The best platform to write and share markdown"
            tag: "notes"
            url: "https://{{ .Values.global.hedgedoc.server.subdomain }}.{{ .Values.global.domain }}/"
          {{- end }}
          {{- if .Values.global.deploy.filebrowser }}
          - name: "File Browser"
            icon: "fas fa-folder-open"
            subtitle: "Access your files through a nice web interface"
            tag: "files"
            url: "https://{{ .Values.global.filebrowser.server.subdomain }}.{{ .Values.global.domain }}/"
          {{- end }}
          {{- if .Values.global.deploy.qbittorrent }}
          - name: "qBittorrent"
            icon: "fa-solid fa-cloud-arrow-down"
            subtitle: "Cross-platform free and open-source BitTorrent client"
            tag: "files"
            url: "https://{{ .Values.global.qbittorrent.server.subdomain }}.{{ .Values.global.domain }}/"
          {{- end }}
          {{- if .Values.global.deploy.send }}
          - name: "Send"
            icon: "fas fa-cloud-arrow-up"
            subtitle: "Encrypt and send files with a link"
            tag: "files"
            url: "https://{{ .Values.global.send.server.subdomain }}.{{ .Values.global.domain }}/"
          {{- end }}
          {{- if .Values.global.deploy.syncthing }}
          - name: "Syncthing"
            icon: "fa-solid fa-rotate"
            subtitle: "Syncthing is a continuous file synchronization program"
            tag: "files"
            url: "https://{{ .Values.global.syncthing.server.subdomain }}.{{ .Values.global.domain }}/"
          {{- end }}
          {{- if .Values.global.deploy.photoprism }}
          - name: "PhotoPrism"
            icon: "fas fa-photo-film"
            subtitle: "AI-Powered Photos App for the Decentralized Web"
            tag: "photos"
            url: "https://{{ .Values.global.photoprism.server.subdomain }}.{{ .Values.global.domain }}/"
          {{- end }}

      - name: "System"
        icon: "fas fa-code-branch"
        items:
          {{- if .Values.global.deploy.gatus }}
          - name: "Status"
            icon: "fas fa-square-check"
            subtitle: "Status page"
            tag: "status"
            url: "https://{{ .Values.global.gatus.server.subdomain }}.{{ .Values.global.domain }}/"
          {{- end }}
          
          {{- if .Values.global.deploy.grafana }}
          - name: "Grafana"
            icon: "fas fa-chart-column"
            subtitle: "Grafana metrics visualization"
            tag: "metrics"
            url: "https://{{ .Values.global.grafana.server.subdomain }}.{{ .Values.global.domain }}/"
          {{- end }}
          
          {{- if .Values.global.deploy.prometheus }}
          - name: "Prometheus"
            icon: "fas fa-chart-bar"
            subtitle: "Prometheus metrics collection"
            tag: "metrics"
            url: "https://{{ .Values.global.prometheus.server.subdomain }}.{{ .Values.global.domain }}/"
          {{- end }}

          {{- if .Values.global.deploy.traefik }}
          - name: "Traefik"
            icon: "fas fa-route"
            subtitle: "Traefik reverse proxy dashboard"
            tag: "metrics"
            url: "https://{{ .Values.global.traefik.server.subdomain }}.{{ .Values.global.domain }}/"
          {{- end }}

          {{- if .Values.global.deploy.authelia }}
          - name: "Authelia"
            icon: "fas fa-lock"
            subtitle: "Authentication frotnend"
            tag: "auth"
            url: "https://{{ .Values.global.authelia.server.subdomain }}.{{ .Values.global.domain }}/"
          {{- end }}

          {{- if .Values.global.deploy.phpldapadmin }}
          - name: "phpLDAPadmin"
            icon: "fas fa-users"
            subtitle: "LDAP users and groups management"
            tag: "auth"
            url: "https://{{ .Values.global.phpldapadmin.server.subdomain }}.{{ .Values.global.domain }}/"
          {{- end }}

          {{- if .Values.global.deploy.adminer }}
          - name: "Adminer"
            icon: "fas fa-database"
            subtitle: "Database management system"
            tag: "database"
            url: "https://{{ .Values.global.adminer.server.subdomain }}.{{ .Values.global.domain }}/"
          {{- end }}

          {{- if .Values.global.deploy.keel }}
          - name: "Keel"
            icon: "fas fa-cloud-arrow-down"
            subtitle: "Automate Kubernetes updates"
            tag: "kubernetes"
            url: "https://{{ .Values.global.keel.server.subdomain }}.{{ .Values.global.domain }}/"
          {{- end }}
