---
hedgedoc:
  # Enable hedgedoc app?
  # type: boolean
  enabled: false

  server:
    # Name of the component.
    # type: string
    name: "hedgedoc-server"

    # Docker image for the Postgres server.
    image:
      # Image name without the tag.
      # type: string
      name: "quay.io/hedgedoc/hedgedoc"

      # Image tag.
      # type: string
      tag: "latest"

      # Image pull policy.
      # type: string
      pullPolicy: "IfNotPresent"

    # Authentication options.
    auth:
      # LDAP group that the user must belong to.
      # This group will be created automatically if it does not exist.
      # type: string
      group: "hedgedoc"

    # Subdomain at which to host the web GUI.
    # type: string
    subdomain: "markdown"

    # Database options.
    database:
      # Name of the database. The database will be created if it does not exist.
      # type: string
      name: "hedgedoc"

      # Role for the database. The role will be created if it does not exist.
      # type: string
      role: "hedgedoc"

      # Role password for the database.
      # type: string
      password: "Password1!"

    # The user ID to run this fileserver at.
    # type: integer
    uid: 1000

    # The group ID to run this fileserver at.
    # type: integer
    gid: 1000

    # Storage options.
    storage:
      # Capacity to request.
      # type: string
      capacity: "1Gi"

      # Storage subdirectory
      # type: string
      dir: "hedgedoc/server"

    # Additional environment variables for the pod.
    # type: map
    # example: [{ "name": "MY_ENV_KEY", "value": "some_value" }]
    env: []

    # The kubernetes service type.
    # type: string
    serviceType: "ClusterIP"

    # Additional annotations to add to the service.
    # type: map
    # example: { "example.com/hello": "world" }
    serviceAnnotations: {}

    # Additional labels to add to the service.
    # type: map
    # example: { "example.com/hello": "world" }
    serviceLabels: {}
    
    # Additional annotations to add to the pod.
    # type: map
    # example: { "example.com/hello": "world" }
    podAnnotations: {}

    # Additional labels to add to the pod.
    # type: map
    # example: { "example.com/hello": "world" }
    podLabels: {}

    # Specify which node or nodes can be used to host this pod.
    # Leave as an empty map to allow the pod to be spawned anywhere.
    # type: map
    # example: { "kubernetes.io/arch": "amd64" }
    nodeSelector: {}

    # Optionally specify how much of each resource the pod will need.
    resources:
      # Maximum limits that the pod can not exceed.
      # Set to ~ or null to disable the resource limits.
      limits:
        # Maximum CPU that the pod can not exceed.
        # type: string
        # example: "1000m"
        cpu: ~
        # Maximum RAM that the pod can not exceed.
        # type: string
        # example: "1024Mi"
        memory: ~
      # Requested limits for scheduling the pod on nodes.
      # Set to ~ or null to disable the resource requests.
      requests:
        # The requested amount of CPU
        # type: string
        # example: "500m"
        cpu: ~
        # The requested amount of CPU
        # type: string
        # example: "512Mi"
        memory: ~
