{{- include "configmap-spec" (dict 
  "Values" .Values
  "Release" .Release
  "Chart" .Chart
  "component" "server") }}
data:
  "configuration.yml": |
    server:
      host: 0.0.0.0
      port: 9091

    jwt_secret: "{{ .Values.server.jwtSecret }}"

    log:
      level: "{{ .Values.server.log.level }}"

    telemetry:
      metrics:
        enabled: true
        address: "tcp://0.0.0.0:9959"

    session:
      name: authelia_session
      secret: "{{ .Values.server.jwtSecret }}"
      expiration: 3600
      inactivity: 300
      domain: "{{ .Values.global.domain }}"

      redis:
        host: "{{ .Chart.Name }}-redis.{{ .Release.Namespace }}.svc.cluster.local"
        port: 6379
        password: "{{ .Values.redis.password }}"

    storage:
      encryption_key: "{{ .Values.server.encryptionKey }}"
      postgres:
        host: "postgres-server.{{ .Release.Namespace }}.svc.cluster.local"
        port: 5432
        database: "{{ .Values.server.database.name }}"
        username: "{{ .Values.server.database.role }}"
        password: "{{ .Values.server.database.password }}"
        ssl:
          mode: "disable"

    regulation:
      max_retries: 3
      find_time: 120
      ban_time: 300

    notifier:
      disable_startup_check: false
      smtp:
        sender: auth@{{ .Values.global.domain }}
        host: "{{ .Chart.Name }}-smtp.{{ .Release.Namespace }}.svc.cluster.local"
        port: 587
        disable_require_tls: true

    access_control:
      default_policy: deny

      rules:
        {{- if and (.Values.global.deploy.homer) (.Values.global.homer.server.auth.enabled) }}
        - domain: "{{ .Values.global.homer.server.subdomain }}{{ if .Values.global.homer.server.subdomain }}.{{ end }}{{ .Values.global.domain }}"
          {{- if .Values.global.homer.server.auth.group }}
          subject: "group:{{ .Values.global.homer.server.auth.group }}"
          {{- end }}
          policy: "one_factor"
        {{- end }}
        {{- if and (.Values.global.deploy.traefik) (.Values.global.traefik.server.auth.enabled) }}
        - domain: "{{ .Values.global.traefik.server.subdomain }}.{{ .Values.global.domain }}"
          subject: "group:{{ .Values.global.traefik.server.auth.group }}"
          policy: "one_factor"
        {{- end }}
        {{- if and (.Values.global.deploy.adminer) (.Values.global.adminer.server.auth.enabled) }}
        - domain: "{{ .Values.global.adminer.server.subdomain }}.{{ .Values.global.domain }}"
          subject: "group:{{ .Values.global.adminer.server.auth.group }}"
          policy: "one_factor"
        {{- end }}
        {{- if and (.Values.global.deploy.prometheus) (.Values.global.prometheus.server.auth.enabled) }}
        - domain: "{{ .Values.global.prometheus.server.subdomain }}.{{ .Values.global.domain }}"
          subject: "group:{{ .Values.global.prometheus.server.auth.group }}"
          policy: "one_factor"
        {{- end }}
        {{- if and (.Values.global.deploy.drawio) (.Values.global.drawio.server.auth.enabled) }}
        - domain: "{{ .Values.global.drawio.server.subdomain }}.{{ .Values.global.domain }}"
          subject: "group:{{ .Values.global.drawio.server.auth.group }}"
          policy: "one_factor"
        {{- end }}
        {{- if and (.Values.global.deploy.haste) (.Values.global.haste.server.auth.enabled) }}
        - domain: "{{ .Values.global.haste.server.subdomain }}.{{ .Values.global.domain }}"
          subject: "group:{{ .Values.global.haste.server.auth.group }}"
          policy: "one_factor"
        {{- end }}
        {{- if and (.Values.global.deploy.qbittorrent) (.Values.global.qbittorrent.server.auth.enabled) }}
        - domain: "{{ .Values.global.qbittorrent.server.subdomain }}.{{ .Values.global.domain }}"
          subject: "group:{{ .Values.global.qbittorrent.server.auth.group }}"
          policy: "one_factor"
        {{- end }}
    authentication_backend:
      password_reset:
        disable: false

      ldap:
        url: "ldap://openldap-server.{{ .Release.Namespace }}.svc.cluster.local"
        start_tls: false
        implementation: "custom"
        tls:
          skip_verify: false
        base_dn: {{ .Values.global.domainComponent }}
        username_attribute: uid
        additional_users_dn: "ou=users"
        users_filter: "(&({username_attribute}={input})(objectClass=person))"
        additional_groups_dn: "ou=groups"
        groups_filter: "(&(uniqueMember={dn})(objectclass=groupOfUniqueNames))"
        group_name_attribute: "cn"
        mail_attribute: "mail"
        display_name_attribute: "cn"
        user: "cn=admin,{{ .Values.global.domainComponent }}"
        password: '{{ .Values.global.openldap.server.password }}'
