{{ include "deployment-spec" (dict 
  "Values" .Values
  "Release" .Release
  "Chart" .Chart
  "component" "server") }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  revisionHistoryLimit: 0
  {{- include "selector-spec" (dict "Chart" .Chart "component" "server") | nindent 2 }}
  template:
    {{- include "metadata-spec" (dict 
      "Values" .Values
      "Release" .Release
      "Chart" .Chart
      "component" "server"
      "annotations" .Values.server.pod.annotations) | nindent 4}}
    spec:
      serviceAccountName: "{{ .Chart.Name }}-server"
      enableServiceLinks: false
      securityContext:
        runAsUser: {{ .Values.server.uid }}
        runAsGroup: {{ .Values.server.gid }}
        fsGroup: {{ .Values.server.gid }}
      {{- with .Values.server.pullSecret }}
      imagePullSecrets:
        - name: "{{ . }}"
      {{- end }}
      containers:
        - name: "{{ .Chart.Name }}-server"
          image: "{{ .Values.server.image.name }}:{{ .Values.server.image.tag }}"
          imagePullPolicy: "{{ .Values.server.image.pullPolicy }}"
          env:
            - name: "DHPARAM_GENERATION"
              value: "false"
            - name: "NODE_ENV"
              value: "production"
            - name: "BASE_URL"
              value: "{{ .Values.server.subdomain }}.{{ .Values.global.domain }}"
            - name: "PORT"
              value: "1443"
            - name: "REDIS_HOST"
              value: "{{ .Chart.Name }}-redis.{{ .Release.Namespace }}.svc.cluster.local"
            - name: "REDIS_PASSWORD"
              value: "{{ .Values.redis.password }}"
            - name: "FILE_DIR"
              value: "/uploads"
            - name: EXPIRE_TIMES_SECONDS
              value: "{{ .Values.server.limits.expireTimesSeconds }}"
            - name: DEFAULT_EXPIRE_SECONDS
              value: "{{ .Values.server.limits.defaultDownloads }}"
            - name: DEFAULT_EXPIRE_SECONDS
              value: "{{ .Values.server.limits.defaultExpireSeconds }}"
            - name: MAX_EXPIRE_SECONDS
              value: "{{ .Values.server.limits.maxExpireSeconds }}"
            - name: DOWNLOAD_COUNTS
              value: "{{ .Values.server.limits.downloadCounts }}"
            - name: MAX_DOWNLOADS
              value: "{{ .Values.server.limits.maxDownloads }}"
            - name: MAX_FILE_SIZE
              value: "{{ .Values.server.limits.maxFileSize }}"
          {{- with .Values.server.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: web
              containerPort: 1443
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: web
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /
              port: web
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: "uploads-volume"
              mountPath: "/uploads"
      nodeSelector:
        {{- toYaml .Values.server.nodeSelector | nindent 8 }}
      volumes:
        - name: "uploads-volume"
          persistentVolumeClaim:
            claimName: "{{ .Chart.Name }}-server-uploads"
