apiVersion: v1
kind: Secret
{{ include "metadata-spec" (dict 
  "Values" .Values
  "Release" .Release
  "Chart" .Chart
  "component" "server") }}
type: "Opaque"
data:
  "{{ .Values.global.domain }}.signing.key": |
    {{ .Values.server.secrets.signingkey | b64enc | nindent 4 }}
