- name: "Set matrix redis facts"
  set_fact:
    matrix_redis_url: "{{ matrix.redis.name }}.{{ common.namespace }}.svc.cluster.local"

- name: "Run deployment"
  include_tasks: "roles/common/tasks/apply.yml"
  vars:
    resources: "{{ role_path }}/templates/redis/"
    name: "{{ matrix.redis.name }}"
    deployment_timeout: 6
    storages: []
