{{- include "configmap-spec" (dict 
  "Values" .Values
  "Release" .Release
  "Chart" .Chart
  "component" "server") }}
data:
  "GITLAB_OMNIBUS_CONFIG": |
    external_url 'https://{{ .Values.server.subdomain }}.{{ .Values.global.domain }}'
    git_data_dirs({ "default" => { "path" => "/git-data" } })
    gitlab_ci['builds_directory'] = '/builds'
    gitlab_rails['shared_path'] = '/shared'
    redis['enable'] = false
    gitlab_rails['redis_host'] = '{{ .Chart.Name }}-redis.{{ .Release.Namespace }}.svc.cluster.local'
    gitlab_rails['redis_port'] = 6379
    gitlab_rails['redis_password'] =  '{{ .Values.redis.password }}'
    nginx['listen_port'] = 80
    nginx['listen_https'] = false
    postgresql['enable'] = false
    
    gitlab_rails['smtp_enable'] = true
    gitlab_rails['smtp_address'] = '{{ .Chart.Name }}-smtp.{{ .Release.Namespace }}.svc.cluster.local'
    gitlab_rails['smtp_port'] = 587
    gitlab_rails['smtp_tls'] = false
    gitlab_rails['smtp_ssl'] = false
    gitlab_rails['smtp_force_ssl'] = false
    gitlab_rails['smtp_domain'] = '{{ .Values.global.domain }}'
    gitlab_rails['smtp_enable_starttls_auto'] = false
    gitlab_rails['smtp_openssl_verify_mode'] = 'none'
    gitlab_rails['gitlab_email_from'] = 'gitlab@{{ .Values.global.domain }}'
    gitlab_rails['gitlab_email_reply_to'] = 'noreply@{{ .Values.global.domain }}'

    gitlab_rails['initial_root_password'] = '{{ .Values.server.auth.password }}'
    gitlab_rails['db_adapter'] = 'postgresql'
    gitlab_rails['db_encoding'] = 'unicode'
    gitlab_rails['db_host'] = 'postgres-server.{{ .Release.Namespace }}.svc.cluster.local'
    gitlab_rails['db_password'] = '{{ .Values.server.database.password }}'
    gitlab_rails['gitlab_shell_ssh_port'] = {{ .Values.server.sshPort }}
    gitlab_rails['ldap_enabled'] = true
    gitlab_rails['prevent_ldap_sign_in'] = false
    gitlab_rails['packages_enabled'] = true
    gitlab_rails['lfs_enabled'] = true
    gitlab_rails['object_store']['enabled'] = true
    gitlab_rails['object_store']['proxy_download'] = true
    gitlab_rails['object_store']['connection'] = {
      'aws_signature_version' => 4,
      'provider' => 'AWS',
      'region' => 'eu-central-1',
      'aws_access_key_id' => '{{ .Values.storage.accessKey }}',
      'aws_secret_access_key' => '{{ .Values.storage.secretKey }}',
      'host' => '{{ .Chart.Name }}-storage.{{ .Release.Namespace }}.svc.cluster.local',
      'endpoint' => 'http://{{ .Chart.Name }}-storage.{{ .Release.Namespace }}.svc.cluster.local:9000',
      'path_style' => true,
      'use_iam_profile' => false
    }
    gitlab_rails['monitoring_whitelist'] = ['0.0.0.0/0']
    gitlab_rails['object_store']['objects']['artifacts']['bucket'] = '{{ .Values.storage.buckets.artifacts }}'
    gitlab_rails['object_store']['objects']['external_diffs']['bucket'] = '{{ .Values.storage.buckets.diffs }}'
    gitlab_rails['object_store']['objects']['lfs']['bucket'] = '{{ .Values.storage.buckets.lfs }}'
    gitlab_rails['object_store']['objects']['uploads']['bucket'] = '{{ .Values.storage.buckets.uploads }}'
    gitlab_rails['object_store']['objects']['packages']['bucket'] = '{{ .Values.storage.buckets.packages }}'
    gitlab_rails['object_store']['objects']['dependency_proxy']['bucket'] = '{{ .Values.storage.buckets.dependency }}'
    gitlab_rails['object_store']['objects']['terraform_state']['bucket'] = '{{ .Values.storage.buckets.terraform }}'
    gitlab_rails['object_store']['objects']['pages']['bucket'] = '{{ .Values.storage.buckets.pages }}'
    grafana['enable'] = false
    prometheus['enable'] = false
    prometheus_monitoring['enable'] = false
    alertmanager['enable'] = false
    pages_nginx['enable'] = true
    pages_external_url 'https://{{ .Values.server.subdomainPages }}.{{ .Values.global.domain }}'
    pages_nginx['listen_port'] = 82
    pages_nginx['listen_https'] = false
    pages_nginx['proxy_set_headers'] = {
      "X-Forwarded-Proto" => "https",
      "X-Forwarded-Ssl" => "on"
    }
    gitlab_pages['inplace_chroot'] = true
    registry['enable'] = true
    registry['storage'] = {
      's3' => {
        'accesskey' => '{{ .Values.storage.accessKey }}',
        'secretkey' => '{{ .Values.storage.secretKey }}',
        'bucket' => 'gitlab-registry-storage',
        'region' => 'eu-central-1',
        'regionendpoint' => 'http://{{ .Chart.Name }}-storage.{{ .Release.Namespace }}.svc.cluster.local:9000'
      },
      'redirect' => {
        'disable' => true
      }
    }
    registry_external_url 'https://{{ .Values.server.subdomainRegistry }}.{{ .Values.global.domain }}'
    registry_nginx['enable'] = true
    registry_nginx['listen_port'] = 81
    registry_nginx['listen_https'] = false
    registry_nginx['proxy_set_headers'] = {
      "X-Forwarded-Proto" => "https",
      "X-Forwarded-Ssl" => "on",
      "Host" => "{{ .Values.server.subdomainRegistry }}.{{ .Values.global.domain }}",
      "X-Real-IP" => "$remote_addr",
      "X-Forwarded-For" => "$proxy_add_x_forwarded_for",
      "Upgrade" => "$http_upgrade",
      "Connection" => "$connection_upgrade"
    }
    gitlab_rails['ldap_servers'] = {
    'main' => {
      'label' => 'LDAP',
      'host' =>  'openldap-server.{{ .Release.Namespace }}.svc.cluster.local',
      'port' => 389,
      'uid' => 'uid',
      'encryption' => 'plain',
      'verify_certificates' => true,
      'bind_dn' => 'cn=readonly,{{ .Values.global.domainComponent }}',
      'password' => '{{ .Values.global.openldap.server.readonlyPassword }}',
      'verify_certificates' => false,
      'tls_options' => {
        'ca_file' => '',
        'ssl_version' => '',
        'ciphers' => '',
        'cert' => '',
        'key' => ''
      },
      'timeout' => 10,
      'active_directory' => false,
      'allow_username_or_email_login' => false,
      'block_auto_created_users' => false,
      'base' => 'ou=users,{{ .Values.global.domainComponent }}',
      'user_filter' => '(memberOf=cn={{ .Values.server.auth.group }},ou=groups,{{ .Values.global.domainComponent }})',
      'attributes' => {
        'username' => ['uid', 'userid', 'sAMAccountName'],
        'email' => ['mail', 'email'],
        'name' => 'cn',
        'first_name' => 'givenName',
        'last_name' => 'sn'
      },
      'lowercase_usernames' => false,
      }
    }
