{{- include "configmap-spec" (dict 
  "Values" .Values
  "Release" .Release
  "Chart" .Chart
  "component" "server") }}
data:
  "config.yaml": |
    metrics: true
    endpoints:
      {{- if .Values.global.deploy.authelia }}
      - name: Authelia Web
        group: Authelia
        url: https://traefik-server.{{ .Release.Namespace }}.svc.cluster.local
        interval: 5m
        ui:
          hide-hostname: true
          hide-url: true
        client:
          insecure: true
          timeout: 10s
        headers:
          "Host": "{{ .Values.global.authelia.server.subdomain }}.{{ .Values.global.domain }}"
        conditions:
          - "[STATUS] == any(200)"
      - name: Authelia Server
        group: Authelia
        url: http://{{ .Chart.Name }}-proxy.{{ .Release.Namespace }}.svc.cluster.local/deployment/authelia-server
        interval: 5m
        ui:
          hide-hostname: true
          hide-url: true
        client:
          timeout: 10s
        conditions:
          - "[STATUS] == 200"
      - name: Authelia Redis
        group: Authelia
        url: http://{{ .Chart.Name }}-proxy.{{ .Release.Namespace }}.svc.cluster.local/deployment/authelia-redis
        interval: 5m
        ui:
          hide-hostname: true
          hide-url: true
        client:
          timeout: 10s
        conditions:
          - "[STATUS] == 200"
      - name: Authelia SMTP
        group: Authelia
        url: http://{{ .Chart.Name }}-proxy.{{ .Release.Namespace }}.svc.cluster.local/deployment/authelia-smtp
        interval: 5m
        ui:
          hide-hostname: true
          hide-url: true
        client:
          timeout: 10s
        conditions:
          - "[STATUS] == 200"
      {{- end }}

      {{- if .Values.global.deploy.openldap }}
      - name: OpenLDAP Server
        group: OpenLDAP
        url: http://{{ .Chart.Name }}-proxy.{{ .Release.Namespace }}.svc.cluster.local/deployment/openldap-server
        interval: 5m
        ui:
          hide-hostname: true
          hide-url: true
        client:
          timeout: 10s
        conditions:
          - "[STATUS] == 200"
      {{- end }}

      {{- if .Values.global.deploy.phpldapadmin }}
      - name: phpLDAPAdmin Web
        group: phpLDAPAdmin
        url: https://traefik-server.{{ .Release.Namespace }}.svc.cluster.local
        interval: 5m
        ui:
          hide-hostname: true
          hide-url: true
        client:
          insecure: true
          timeout: 10s
        headers:
          "Host": "{{ .Values.global.phpldapadmin.server.subdomain }}.{{ .Values.global.domain }}"
        conditions:
          - "[STATUS] == any(200)"
      - name: phpLDAPAdmin Server
        group: phpLDAPAdmin
        url: http://{{ .Chart.Name }}-proxy.{{ .Release.Namespace }}.svc.cluster.local/deployment/phpldapadmin-server
        interval: 5m
        ui:
          hide-hostname: true
          hide-url: true
        client:
          timeout: 10s
        conditions:
          - "[STATUS] == 200"
      {{- end }}

      {{- if .Values.global.deploy.postgres }}
      - name: Postgres Server
        group: Postgres
        url: http://{{ .Chart.Name }}-proxy.{{ .Release.Namespace }}.svc.cluster.local/deployment/postgres-server
        interval: 5m
        ui:
          hide-hostname: true
          hide-url: true
        client:
          timeout: 10s
        conditions:
          - "[STATUS] == 200"
      - name: Postgres Backup
        group: Postgres
        url: http://{{ .Chart.Name }}-proxy.{{ .Release.Namespace }}.svc.cluster.local/deployment/postgres-backup
        interval: 5m
        ui:
          hide-hostname: true
          hide-url: true
        client:
          timeout: 10s
        conditions:
          - "[STATUS] == 200"
      {{- end }}

      {{- if .Values.global.deploy.loki }}
      - name: Loki Server
        group: Loki
        url: http://{{ .Chart.Name }}-proxy.{{ .Release.Namespace }}.svc.cluster.local/deployment/loki-server
        interval: 5m
        ui:
          hide-hostname: true
          hide-url: true
        client:
          timeout: 10s
        conditions:
          - "[STATUS] == 200"
      - name: Loki Cassandra
        group: Loki
        url: http://{{ .Chart.Name }}-proxy.{{ .Release.Namespace }}.svc.cluster.local/deployment/loki-cassandra
        interval: 5m
        ui:
          hide-hostname: true
          hide-url: true
        client:
          timeout: 10s
        conditions:
          - "[STATUS] == 200"
      - name: Loki MinIO
        group: Loki
        url: http://{{ .Chart.Name }}-proxy.{{ .Release.Namespace }}.svc.cluster.local/deployment/loki-minio
        interval: 5m
        ui:
          hide-hostname: true
          hide-url: true
        client:
          timeout: 10s
        conditions:
          - "[STATUS] == 200"
      {{- end }}

      {{- if .Values.global.deploy.prometheus }}
      - name: Prometheus Web
        group: Prometheus
        url: https://traefik-server.{{ .Release.Namespace }}.svc.cluster.local
        interval: 5m
        ui:
          hide-hostname: true
          hide-url: true
        client:
          insecure: true
          timeout: 10s
        headers:
          "Host": "{{ .Values.global.prometheus.server.subdomain }}.{{ .Values.global.domain }}"
        conditions:
          - "[STATUS] == any(200, 401)"
      - name: Prometheus Server
        group: Prometheus
        url: http://{{ .Chart.Name }}-proxy.{{ .Release.Namespace }}.svc.cluster.local/deployment/prometheus-server
        interval: 5m
        ui:
          hide-hostname: true
          hide-url: true
        client:
          timeout: 10s
        conditions:
          - "[STATUS] == 200"
      {{- end }}

      {{- if .Values.global.deploy.errorpage }}
      - name: Error Page Web
        group: Error Page
        url: https://traefik-server.{{ .Release.Namespace }}.svc.cluster.local
        interval: 5m
        ui:
          hide-hostname: true
          hide-url: true
        client:
          insecure: true
          timeout: 10s
        headers:
          "Host": "error.{{ .Values.global.domain }}"
        conditions:
          - "[STATUS] == any(200, 404)"
      - name: Error Page Server
        group: Error Page
        url: http://{{ .Chart.Name }}-proxy.{{ .Release.Namespace }}.svc.cluster.local/deployment/errorpage-server
        interval: 5m
        ui:
          hide-hostname: true
          hide-url: true
        client:
          timeout: 10s
        conditions:
          - "[STATUS] == 200"
      {{- end }}

      {{- if .Values.global.deploy.grafana }}
      - name: Grafana Web
        group: Grafana
        url: https://traefik-server.{{ .Release.Namespace }}.svc.cluster.local
        interval: 5m
        ui:
          hide-hostname: true
          hide-url: true
        client:
          insecure: true
          timeout: 10s
        headers:
          "Host": "{{ .Values.global.grafana.server.subdomain }}.{{ .Values.global.domain }}"
        conditions:
          - "[STATUS] == any(200)"
      - name: Grafana Server
        group: Grafana
        url: http://{{ .Chart.Name }}-proxy.{{ .Release.Namespace }}.svc.cluster.local/deployment/grafana-server
        interval: 5m
        ui:
          hide-hostname: true
          hide-url: true
        client:
          timeout: 10s
        conditions:
          - "[STATUS] == 200"
      - name: Grafana Redis
        group: Grafana
        url: http://{{ .Chart.Name }}-proxy.{{ .Release.Namespace }}.svc.cluster.local/deployment/grafana-redis
        interval: 5m
        ui:
          hide-hostname: true
          hide-url: true
        client:
          timeout: 10s
        conditions:
          - "[STATUS] == 200"
      - name: Grafana MinIO
        group: Grafana
        url: http://{{ .Chart.Name }}-proxy.{{ .Release.Namespace }}.svc.cluster.local/deployment/grafana-minio
        interval: 5m
        ui:
          hide-hostname: true
          hide-url: true
        client:
          timeout: 10s
        conditions:
          - "[STATUS] == 200"
      - name: Grafana SMTP
        group: Grafana
        url: http://{{ .Chart.Name }}-proxy.{{ .Release.Namespace }}.svc.cluster.local/deployment/grafana-smtp
        interval: 5m
        ui:
          hide-hostname: true
          hide-url: true
        client:
          timeout: 10s
        conditions:
          - "[STATUS] == 200"
      {{- end }}

      {{- if .Values.global.deploy.homer }}
      - name: Homer Web
        group: Homer
        url: https://traefik-server.{{ .Release.Namespace }}.svc.cluster.local
        interval: 5m
        ui:
          hide-hostname: true
          hide-url: true
        client:
          insecure: true
          timeout: 10s
        headers:
          "Host": "{{ .Values.global.homer.server.subdomain }}{{ if .Values.global.homer.server.subdomain }}.{{ end }}{{ .Values.global.domain }}"
        conditions:
          - "[STATUS] == any(200, 401)"
      - name: Homer Server
        group: Homer
        url: http://{{ .Chart.Name }}-proxy.{{ .Release.Namespace }}.svc.cluster.local/deployment/homer-server
        interval: 5m
        ui:
          hide-hostname: true
          hide-url: true
        client:
          timeout: 10s
        conditions:
          - "[STATUS] == 200"
      {{- end }}

      {{- if .Values.global.deploy.adminer }}
      - name: Adminer Web
        group: Adminer
        url: https://traefik-server.{{ .Release.Namespace }}.svc.cluster.local
        interval: 5m
        ui:
          hide-hostname: true
          hide-url: true
        client:
          insecure: true
          timeout: 10s
        headers:
          "Host": "{{ .Values.global.adminer.server.subdomain }}.{{ .Values.global.domain }}"
        conditions:
          - "[STATUS] == any(200, 401)"
      - name: Adminer Server
        group: Adminer
        url: http://{{ .Chart.Name }}-proxy.{{ .Release.Namespace }}.svc.cluster.local/deployment/adminer-server
        interval: 5m
        ui:
          hide-hostname: true
          hide-url: true
        client:
          timeout: 10s
        conditions:
          - "[STATUS] == 200"
      {{- end }}

      {{- if .Values.global.deploy.keel }}
      - name: Keel Web
        group: Keel
        url: https://traefik-server.{{ .Release.Namespace }}.svc.cluster.local
        interval: 5m
        ui:
          hide-hostname: true
          hide-url: true
        client:
          insecure: true
          timeout: 10s
        headers:
          "Host": "{{ .Values.global.keel.server.subdomain }}.{{ .Values.global.domain }}"
        conditions:
          - "[STATUS] == any(200)"
      - name: Keel Server
        group: Keel
        url: http://{{ .Chart.Name }}-proxy.{{ .Release.Namespace }}.svc.cluster.local/deployment/keel-server
        interval: 5m
        ui:
          hide-hostname: true
          hide-url: true
        client:
          timeout: 10s
        conditions:
          - "[STATUS] == 200"
      {{- end }}
