{{ include "ingressroute-spec" (dict 
  "Values" .Values
  "Release" .Release
  "Chart" .Chart
  "component" "server") }}
  routes:
    - match: Host(`{{ .Values.gatus.server.subdomain }}.{{ .Values.global.domain }}`)
      kind: Rule
      services:
       - name: "{{ .Chart.Name }}-server"
         namespace: "{{ .Release.Namespace }}"
         port: 8080
