{{ include "service-spec" (dict 
  "Values" .Values
  "Release" .Release
  "Chart" .Chart
  "component" "kroki"
  "service" .Values.kroki.service) }}
  ports:
    - port: 8000
      protocol: "TCP"
      name: "web"
