- name: "Run storage setup"
  include_tasks: "roles/k8s/tasks/storage.yml"
  vars:
    name: "{{ nextcloud.minio.name }}"
    storage:
      dir: "{{ nextcloud.minio.storage.dir }}"
      mode: "0700"
      uid: 1000
      gid: 1000

- set_fact:
    nextcloud_minio_url: "{{ nextcloud.minio.name }}.{{ common.namespace }}.svc.cluster.local"

- name: "Run deployment"
  include_tasks: "roles/k8s/tasks/apply.yml"
  vars:
    resources: "{{ role_path }}/templates/minio/"
    name: "{{ nextcloud.minio.name }}"
    deployment_timeout: 6
