- name: "Run storage setup"
  include_tasks: "roles/k8s/tasks/storage.yml"
  vars:
    name: "{{ nextcloud.server.name }}"
    storage:
      dir: "{{ nextcloud.server.storage.dir }}"
      mode: "0770"
      uid: 33
      gid: 33

- set_fact:
    nextcloud_server_url: "{{ nextcloud.server.name }}.{{ common.namespace }}.svc.cluster.local"
    group_ldif: "{{ lookup('template', role_path + '/templates/group.ldif.j2') }}"

- name: "Run deployment"
  include_tasks: "roles/k8s/tasks/apply.yml"
  vars:
    resources: "{{ role_path }}/templates/server/"
    name: "{{ nextcloud.server.name }}"
    deployment_timeout: 12
