- name: "Set joplin server facts"
  set_fact:
    joplin_server_url: "{{ joplin.server.name }}.{{ common.namespace }}.svc.cluster.local"

- name: "Run deployment"
  include_tasks: "roles/common/tasks/apply.yml"
  vars:
    resources: "{{ role_path }}/templates/server/"
    name: "{{ joplin.server.name }}"
    deployment_timeout: 6
    storages: []
