- name: "Set mariadb server facts"
  set_fact:
    mariadb_server_url: "{{ mariadb.server.name }}.{{ common.namespace }}.svc.cluster.local"
    mariadb_container_add_database_path: "{{ role_path }}/templates/containers/add_database.yml.j2"

- name: "Run deployment"
  include_tasks: "roles/common/tasks/apply.yml"
  vars:
    resources: "{{ role_path }}/templates/server/"
    name: "{{ mariadb.server.name }}"
    deployment_timeout: 12
    storages:
      - dir: "{{ mariadb.server.storage.dir }}"
        mode: "0770"
        uid: 1000
        gid: 1001
