- name: "Set send redis facts"
  set_fact:
    send_redis_url: "{{ send.redis.name }}.{{ common.namespace }}.svc.cluster.local"

- name: "Run deployment"
  include_tasks: "roles/common/tasks/apply.yml"
  vars:
    resources: "{{ role_path }}/templates/redis/"
    name: "{{ send.redis.name }}"
    deployment_timeout: 6
    storages:
      - dir: "{{ send.redis.storage.dir }}"
        mode: "0775"
        uid: 999
        gid: 999
