- name: "Set send server facts"
  set_fact:
    send_server_url: "{{ send.server.name }}.{{ common.namespace }}.svc.cluster.local"

- name: "Run deployment"
  include_tasks: "roles/common/tasks/apply.yml"
  vars:
    resources: "{{ role_path }}/templates/server/"
    name: "{{ send.server.name }}"
    deployment_timeout: 6
    storages:
      - dir: "{{ send.server.storage.dir }}"
        mode: "0775"
        uid: "{{ send.server.uid }}"
        gid: "{{ send.server.gid }}"