- name: "Set qbittorrent server facts"
  set_fact:
    qbittorrent_server_url: "{{ qbittorrent.server.name }}.{{ common.namespace }}.svc.cluster.local"

- name: "Run deployment"
  include_tasks: "roles/common/tasks/apply.yml"
  vars:
    resources: "{{ role_path }}/templates/server/"
    name: "{{ qbittorrent.server.name }}"
    deployment_timeout: 12
    storages:
      - dir: "{{ qbittorrent.server.storageConfig.dir }}"
        setup: "{{ qbittorrent.server.storageConfig.setup | default(omit) }}"
        host: "{{ qbittorrent.server.storageConfig.host | default(omit) }}"
        nfs: "{{ qbittorrent.server.storageConfig.nfs | default(omit) }}"
        mode: "0770"
        uid: "{{ qbittorrent.server.uid }}"
        gid: "{{ qbittorrent.server.gid }}"
      - dir: "{{ qbittorrent.server.storageDownloads.dir }}"
        setup: "{{ qbittorrent.server.storageDownloads.setup | default(omit) }}"
        host: "{{ qbittorrent.server.storageDownloads.host | default(omit) }}"
        nfs: "{{ qbittorrent.server.storageDownloads.nfs | default(omit) }}"
        mode: "0775"
        uid: "{{ qbittorrent.server.uid }}"
        gid: "{{ qbittorrent.server.gid }}"
