{{ include "clusterrole-spec" (dict 
  "Values" .Values
  "Release" .Release
  "Chart" .Chart
  "component" "server") }}
rules:
  - apiGroups:
      - ''
    resources:
      - 'nodes'
      - 'nodes/proxy'
      - 'nodes/metrics'
      - 'services'
      - 'endpoints'
      - 'pods'
      - 'ingresses'
      - 'configmaps'
    verbs:
      - 'get'
      - 'list'
      - 'watch'
  - apiGroups:
      - 'extensions'
      - 'networking.k8s.io'
    resources:
      - 'ingresses/status'
      - 'ingresses'
    verbs:
      - 'get'
      - 'list'
      - 'watch'
  - nonResourceURLs:
      - '/metrics'
    verbs:
      - 'get'
