---
filebrowser:
  # Enable FileBrowser app?
  # type: boolean
  enabled: false

  server:
    # Name of the component.
    # type: string
    name: "filebrowser-server"

    # Docker image for the Postgres server.
    image:
      # Image name without the tag.
      # type: string
      name: "docker.io/filebrowser/filebrowser"

      # Image tag.
      # type: string
      tag: "v2.22.4"

      # Image pull policy.
      # type: string
      pullPolicy: "IfNotPresent"

    # Subdomain at which to host the web GUI.
    # type: string
    subdomain: "files"

    # Authentication options.
    auth:
      # Use Authelia authentication for the web GUI? This will utilize LDAP.
      # It would be very dangerous to disable this.
      # type: boolean
      enabled: true

      # LDAP group that the user must belong to.
      # This group will be created automatically if it does not exist.
      # type: string
      group: "filebrowser"

    # The user ID to run this fileserver at.
    # type: integer
    uid: 1000

    # The group ID to run this fileserver at.
    # type: integer
    gid: 1000

    # Storage options for the configuration and database.
    dataStorage:
      # Capacity to request.
      # type: string
      capacity: "1Gi"

      # Storage subdirectory
      # type: string
      dir: "filebrowser/server/db"

    # Storage options for the files.
    filesStorage:
      # Capacity to request.
      # type: string
      capacity: "20Gi"

      # Storage subdirectory
      # type: string
      dir: "filebrowser/server/files"

    # Additional environment variables for the pod.
    # type: map
    # example: [{ "name": "MY_ENV_KEY", "value": "some_value" }]
    env: []

    # The kubernetes service type.
    # type: string
    serviceType: "ClusterIP"

    # Additional annotations to add to the service.
    # type: map
    # example: { "example.com/hello": "world" }
    serviceAnnotations: {}

    # Additional labels to add to the service.
    # type: map
    # example: { "example.com/hello": "world" }
    serviceLabels: {}
    
    # Additional annotations to add to the pod.
    # type: map
    # example: { "example.com/hello": "world" }
    podAnnotations: {}

    # Additional labels to add to the pod.
    # type: map
    # example: { "example.com/hello": "world" }
    podLabels: {}

    # Specify which node or nodes can be used to host this pod.
    # Leave as an empty map to allow the pod to be spawned anywhere.
    # type: map
    # example: { "kubernetes.io/arch": "amd64" }
    nodeSelector: {}

    # Optionally specify how much of each resource the pod will need.
    resources:
      # Maximum limits that the pod can not exceed.
      # Set to ~ or null to disable the resource limits.
      limits:
        # Maximum CPU that the pod can not exceed.
        # type: string
        # example: "1000m"
        cpu: ~
        # Maximum RAM that the pod can not exceed.
        # type: string
        # example: "1024Mi"
        memory: ~
      # Requested limits for scheduling the pod on nodes.
      # Set to ~ or null to disable the resource requests.
      requests:
        # The requested amount of CPU
        # type: string
        # example: "500m"
        cpu: ~
        # The requested amount of CPU
        # type: string
        # example: "512Mi"
        memory: ~
