apiVersion: v1
kind: Secret
{{ include "metadata-spec" (dict 
  "Values" .Values
  "Release" .Release
  "Chart" .Chart
  "component" "server") }}
type: "Opaque"
data:
  cmdDbUrl: "{{ (printf "postgres://%s:%s@postgres-server.%s.svc.cluster.local:5432/%s" .Values.server.database.role .Values.server.database.password .Release.Namespace .Values.server.database.name) | b64enc }}"
  ldapPassword: "{{ .Values.global.openldap.server.readonlyPassword | b64enc }}"
