{{ include "role-spec" (dict 
  "Values" .Values
  "Release" .Release
  "Chart" .Chart
  "component" "runner") }}
  - apiGroups:
      - ''
    resources:
      - 'pods/log'
    verbs:
      - 'get'
  - apiGroups:
      - ''
    resources:
      - 'pods/attach'
    verbs:
      - 'get'
      - 'create'
      - 'patch'
      - 'delete'
  - apiGroups:
      - ''
    resources:
      - 'pods/exec'
    verbs:
      - 'create'
      - 'patch'
      - 'delete'
  - apiGroups:
      - ''
    resources:
      - 'pods'
      - 'secrets'
      - 'configmaps'
    verbs:
      - '*'
