- name: "Set homer server facts"
  set_fact:
    homer_server_url: "{{ homer.server.name }}.{{ common.namespace }}.svc.cluster.local"
    config_yml: "{{ lookup('template', role_path + '/templates/config.yml.j2') }}"

- name: "Run deployment"
  include_tasks: "roles/common/tasks/apply.yml"
  vars:
    resources: "{{ role_path }}/templates/server/"
    name: "{{ homer.server.name }}"
    deployment_timeout: 6
    storages: []
