- name: "Set onlyoffice redis facts"
  set_fact:
    onlyoffice_redis_url: "{{ onlyoffice.redis.name }}.{{ common.namespace }}.svc.cluster.local"

- name: "Run deployment"
  include_tasks: "roles/common/tasks/apply.yml"
  vars:
    resources: "{{ role_path }}/templates/redis/"
    name: "{{ onlyoffice.redis.name }}"
    deployment_timeout: 12
    storages: []
