- name: "Set onlyoffice server facts"
  set_fact:
    onlyoffice_server_url: "{{ onlyoffice.server.name }}.{{ common.namespace }}.svc.cluster.local"

- name: "Run deployment"
  include_tasks: "roles/common/tasks/apply.yml"
  vars:
    resources: "{{ role_path }}/templates/server/"
    name: "{{ onlyoffice.server.name }}"
    deployment_timeout: 12
    storages:
      - dir: "{{ onlyoffice.server.storage.dir }}"
        setup: "{{ onlyoffice.server.storage.setup | default(omit) }}"
        host: "{{ onlyoffice.server.storage.host | default(omit) }}"
        nfs: "{{ onlyoffice.server.storage.nfs | default(omit) }}"
        mode: "0775"
        uid: 0
        gid: 0
