- set_fact:
    postgres_server_url: "{{ postgres.server.name }}.{{ common.namespace }}.svc.cluster.local"

- name: "Run deployment"
  include_tasks: "roles/k8s/tasks/apply.yml"
  vars:
    resources: "{{ role_path }}/templates/server/"
    name: "{{ postgres.server.name }}"
    deployment_timeout: 12
    storages:
      - dir: "{{ postgres.server.storage.dir }}"
        mode: "0700"
        uid: 999
        gid: 0
