- set_fact:
    authelia_server_url: "{{ authelia.server.name }}.{{ common.namespace }}.svc.cluster.local"
    configuration_yml: "{{ lookup('template', role_path + '/templates/configuration.yml.j2') }}"

- name: "Run deployment"
  include_tasks: "roles/k8s/tasks/apply.yml"
  vars:
    resources: "{{ role_path }}/templates/server/"
    name: "{{ authelia.server.name }}"
    deployment_timeout: 12
    storages: []
