{{ $configMapHash := include (print $.Template.BasePath "/proxy/configmap.yaml") . | sha256sum }}
{{ include "deployment-spec" (dict 
  "Values" .Values
  "Release" .Release
  "Chart" .Chart
  "component" "proxy") }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  revisionHistoryLimit: 0
  {{- include "selector-spec" (dict "Chart" .Chart "component" "proxy") | nindent 2 }}
  template:
    {{- include "metadata-spec" (dict 
      "Values" .Values
      "Release" .Release
      "Chart" .Chart
      "component" "proxy"
      "annotations" .Values.proxy.pod.annotations
      "checksum" $configMapHash) | nindent 4}}
    spec:
      serviceAccountName: "{{ .Chart.Name }}-proxy"
      enableServiceLinks: false
      securityContext:
        runAsUser: {{ .Values.proxy.uid }}
        runAsGroup: {{ .Values.proxy.gid }}
        fsGroup: {{ .Values.proxy.gid }}
      {{- with .Values.proxy.pullSecret }}
      imagePullSecrets:
        - name: "{{ . }}"
      {{- end }}
      containers:
        - name: "{{ .Chart.Name }}-proxy"
          image: "{{ .Values.proxy.image.name }}:{{ .Values.proxy.image.tag }}"
          imagePullPolicy: "{{ .Values.proxy.image.pullPolicy }}"
          env:
            - name: KUBERNETES_NAMESPACE
              value: "{{ .Release.Namespace }}"
          {{- with .Values.proxy.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: web
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: web
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /
              port: web
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          resources:
            {{- toYaml .Values.proxy.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: "config-volume"
              mountPath: "/app/main.py"
              subPath: "main.py"
              readOnly: true
      nodeSelector:
        {{- toYaml .Values.proxy.nodeSelector | nindent 8 }}
      volumes:
        - name: "config-volume"
          configMap:
            name: "{{ .Chart.Name }}-proxy"
            optional: false
            items:
              - key: "main.py"
                path: "main.py"
