{{ include "role-spec" (dict 
  "Values" .Values
  "Release" .Release
  "Chart" .Chart
  "component" "proxy") }}
  - apiGroups:
      - "apps"
    resources:
      - "deployments"
    verbs:
      - "get"
      - "list"
