- name: "Set vigil server facts"
  set_fact:
    vigil_proxy_url: "{{ vigil.proxy.name }}.{{ common.namespace }}.svc.cluster.local"
    main_py: "{{ lookup('file', role_path + '/templates/main.py') }}"

- name: "Run deployment"
  include_tasks: "roles/common/tasks/apply.yml"
  vars:
    resources: "{{ role_path }}/templates/proxy/"
    name: "{{ vigil.proxy.name }}"
    deployment_timeout: 6
    storages: []
