- name: "Set vigil server facts"
  set_fact:
    vigil_server_url: "{{ vigil.server.name }}.{{ common.namespace }}.svc.cluster.local"
    vigil_cfg: "{{ lookup('template', role_path + '/templates/vigil.cfg.j2') }}"

- name: "Run deployment"
  include_tasks: "roles/common/tasks/apply.yml"
  vars:
    resources: "{{ role_path }}/templates/server/"
    name: "{{ vigil.server.name }}"
    deployment_timeout: 6
    storages: []
