- name: "Set adminer server facts"
  set_fact:
    adminer_server_url: "{{ adminer.server.name }}.{{ common.namespace }}.svc.cluster.local"

- name: "Run deployment"
  include_tasks: "roles/common/tasks/apply.yml"
  vars:
    resources: "{{ role_path }}/templates/server/"
    name: "{{ adminer.server.name }}"
    deployment_timeout: 12
