{{- if .Values.server.vpn.enabled }}
apiVersion: v1
kind: Secret
{{ include "metadata-spec" (dict 
  "Values" .Values
  "Release" .Release
  "Chart" .Chart
  "component" "server") }}
type: "Opaque"
data:
  vpnUsername: "{{ .Values.server.vpn.username | b64enc }}"
  vpnPassword: "{{ .Values.server.vpn.password | b64enc }}"
{{- end }}
