{{- include "configmap-spec" (dict 
  "Values" .Values
  "Release" .Release
  "Chart" .Chart
  "component" "nginx") }}
data:
  "matrix.conf": |
    server {
      listen         80 default_server;
      server_name    {{ $.Values.server.subdomain }}.{{ $.Values.global.domain }};

    {{- range $type, $config := .Values.server.workers }}
    {{- if and $config.enabled $config.paths }}
    {{- range $path := $config.paths }}
      location {{ (eq $type "homeserver") | ternary "" "~*" }} {{ $path }} {
        resolver 127.0.0.11 valid=10s ipv6=off;
        proxy_pass http://{{ $.Chart.Name }}-server-{{ $type | replace "_" "-" }}.{{ $.Release.Namespace }}.svc.cluster.local:8008;
        proxy_set_header X-Forwarded-For {{ "$remote_addr" }};
        client_max_body_size 128m;
      }
    {{- end }}
    {{- end }}
    {{- end }}
      location /.well-known/matrix/ {
        root /var/www/;
        default_type application/json;
        add_header Access-Control-Allow-Origin  *;
      }

      location / {
        return 301 https://{{ $.Values.element.subdomain }}.{{ $.Values.global.domain }};
      }
    }

    server {
      listen         80;
      server_name    {{ $.Values.global.domain }};

      location /.well-known/matrix/ {
        root /var/www/;
        default_type application/json;
        add_header Access-Control-Allow-Origin  *;
      }
    }

  client: |
    {
      "m.homeserver": {
        "base_url": "https://{{ .Values.server.subdomain }}.{{ .Values.global.domain }}"
      }
    }
  
  server: |
    {
      "m.server": "{{ .Values.server.subdomain }}.{{ .Values.global.domain }}:443"
    }
