- name: "Set postgres backup facts"
  set_fact:
    postgres_backup_url: "{{ postgres.backup.name }}.{{ common.namespace }}.svc.cluster.local"

- name: "Run deployment"
  include_tasks: "roles/common/tasks/apply.yml"
  vars:
    resources: "{{ role_path }}/templates/backup/"
    name: "{{ postgres.backup.name }}"
    deployment_timeout: 12
    storages:
      - dir: "{{ postgres.backup.storage.dir }}"
        setup: "{{ postgres.backup.storage.setup | default(omit) }}"
        host: "{{ postgres.backup.storage.host | default(omit) }}"
        nfs: "{{ postgres.backup.storage.nfs | default(omit) }}"
        mode: "0775"
        uid: "{{ postgres.backup.uid }}"
        gid: "{{ postgres.backup.gid }}"
