- name: "Set syncthing server facts"
  set_fact:
    syncthing_server_url: "{{ syncthing.server.name }}.{{ common.namespace }}.svc.cluster.local"

- name: "Run deployment"
  include_tasks: "roles/common/tasks/apply.yml"
  vars:
    resources: "{{ role_path }}/templates/server/"
    name: "{{ syncthing.server.name }}"
    deployment_timeout: 6
    storages:
      - dir: "{{ syncthing.server.dataStorage.dir }}"
        mode: "0755"
        uid: "{{ syncthing.server.uid }}"
        gid: "{{ syncthing.server.gid }}"
        host: "{{ syncthing.server.dataStorage.host | default(omit) }}"
        nfs: "{{ syncthing.server.dataStorage.nfs | default(omit) }}"
      - dir: "{{ syncthing.server.filesStorage.dir }}"
        mode: "0755"
        uid: "{{ syncthing.server.uid }}"
        gid: "{{ syncthing.server.gid }}"
        host: "{{ syncthing.server.filesStorage.host | default(omit) }}"
        nfs: "{{ syncthing.server.filesStorage.nfs | default(omit) }}"
