- name: "Set drawio server facts"
  set_fact:
    drawio_server_url: "{{ drawio.server.name }}.{{ common.namespace }}.svc.cluster.local"

- name: "Run deployment"
  include_tasks: "roles/common/tasks/apply.yml"
  vars:
    resources: "{{ role_path }}/templates/server/"
    name: "{{ drawio.server.name }}"
    deployment_timeout: 12
    storages: []
