{{ include "deployment-spec" (dict 
  "Values" .Values
  "Release" .Release
  "Chart" .Chart
  "component" "server") }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  revisionHistoryLimit: 0
  {{- include "selector-spec" (dict "Chart" .Chart "component" "server") | nindent 2 }}
  template:
    {{- include "metadata-spec" (dict 
      "Values" .Values
      "Release" .Release
      "Chart" .Chart
      "component" "server"
      "annotations" .Values.server.pod.annotations) | nindent 4}}
    spec:
      serviceAccountName: "{{ .Chart.Name }}-server"
      enableServiceLinks: false
      securityContext:
        runAsUser: {{ .Values.server.uid }}
        runAsGroup: {{ .Values.server.gid }}
        fsGroup: {{ .Values.server.gid }}
      {{- with .Values.server.pullSecret }}
      imagePullSecrets:
        - name: "{{ . }}"
      {{- end }}
      containers:
        - name: "{{ .Chart.Name }}-server"
          image: "{{ .Values.server.image.name }}:{{ .Values.server.image.tag }}"
          imagePullPolicy: "{{ .Values.server.image.pullPolicy }}"
          env:
            - name: "APPSMITH_DISABLE_INTERCOM"
              value: "true"
            - name: "APPSMITH_MAIL_ENABLED"
              value: "true"
            - name: "APPSMITH_MAIL_FROM"
              value: "appsmith@{{ .Values.global.domain }}"
            - name: "APPSMITH_MAIL_HOST"
              value: "{{ .Chart.Name }}-smtp.{{ .Release.Namespace }}.svc.cluster.local"
            - name: "APPSMITH_MAIL_PORT"
              value: "587"
            - name: "APPSMITH_MAIL_SMTP_TLS_ENABLED"
              value: "false"
            - name: "APPSMITH_MAIL_SMTP_AUTH"
              value: "false"
            - name: "APPSMITH_SIGNUP_DISABLED"
              value: "{{ .Values.server.signup.enabled | ternary "false" "true" }}"
            - name: "APPSMITH_ADMIN_EMAILS"
              value: "{{ .Values.server.signup.adminEmails }}"
          {{- with .Values.server.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: web
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: web
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /
              port: web
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: data-volume
              mountPath: "/appsmith-stacks"
      nodeSelector:
        {{- toYaml .Values.server.nodeSelector | nindent 8 }}
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: "{{ .Chart.Name }}-server-data"
