{{- if and (.Values.traefik.server.certs.certFile) (.Values.traefik.server.certs.keyFile) }}
apiVersion: v1
kind: Secret
{{ include "metadata-spec" (dict 
  "Values" .Values
  "Release" .Release
  "Chart" .Chart
  "component" "server") }}
type: "Opaque"
data:
  "cert.pem": "{{ .Values.traefik.server.certs.certFile | b64enc }}"
  "key.pem": "{{ .Values.traefik.server.certs.keyFile | b64enc }}"
{{- end }}
